### ISSUE TITLE
Alias sync with Markdown links

### ISSUE THREAD

**Issue by franco-ruggeri** [basham/obsidian-alias-from-heading#11]
Hi, thanks a lot for this useful plugin.

I just tried to switch off the "Use [[Wikilinks]]" setting because I'd like to have plain Markdown links that can easily be exported or used in other apps. However, the automatic sync when I change the H1 heading does not work with Markdown links. 

Is that something that could be added?

**Comment by basham** [comment]
This is resolved as of v1.1. Thanks for posting the issue!
