### ISSUE TITLE
Unlinked mentions not detected

### ISSUE THREAD

**Issue by franco-ruggeri** [basham/obsidian-alias-from-heading#12]
A nice Obsidian feature is that unlinked mentions to filenames or aliases are listed, so it is easy to detect if a link between notes is missing. However, the unlinked mentions do not work with the alias from heading.

Example:
<img width="1021" alt="image" src="https://github.com/basham/obsidian-alias-from-heading/assets/38300576/3a9b402d-02f0-4ee6-ba52-49079f9b5777">

- Current behavior: "Ciao1" (standard alias) is detected as an unlinked mention, but "Ciao2" (alias from heading) is not.
- Expected behavior: "Ciao2" should be treated as an alias and detected as an unlinked mention.

It would be great to fix this.

**Comment by basham** [comment]
This is resolved as of v1.1.1. Thanks for posting the issue!
