### ISSUE TITLE
The plugin does not allow other plugins to run

### ISSUE THREAD

**Issue by ghost** [basham/obsidian-alias-from-heading#14]
First of all, thank you so much for this plugin, it is extremely useful, great work!

After the last update, I cannot run some plugins while having enabled the `alias-from-heading` plugin.
For example, when I try to run [Excalidraw](https://github.com/zsviczian/obsidian-excalidraw-plugin) I cannot create a new drawing and this error appears:

![image](https://github.com/basham/obsidian-alias-from-heading/assets/167272398/013a93a4-ada7-4369-b8cd-7bdeb914fca5)

Same happens when trying to create a new note in a specific folder with the plugin [Advanced New File](https://github.com/vanadium23/obsidian-advanced-new-file)

![image](https://github.com/basham/obsidian-alias-from-heading/assets/167272398/34001eb8-4004-4100-863b-a027b1c081d8)

I installed manually the version 1.0.14 and everything works fine, the problem appears from version 1.1.0

![image](https://github.com/basham/obsidian-alias-from-heading/assets/167272398/48f67c8d-405d-4595-ba7b-4327d96d0f69)

**Comment by basham** [comment]
Thanks for posting the issue! It is fixed in v1.1.2.
