### ISSUE TITLE
YAML compatibility - clarification

### ISSUE THREAD

**Issue by jebeaudoin** [basham/obsidian-alias-from-heading#2]
I really love the concept of this plugin because I use the "relative path to file" link format, which is practically unreadable when rendered. Lately, I've been using YAML aliases to generate a readable link.

I need a point of clarification, however. It appears that if the "aliases" key is present in a note's YAML, the ability to link to that note from its first header is disabled. Is that the case?

**Example**

```
Filename: Note A
---
Aliases: 
- 'Linus'
---

# Charlie Brown
```

When trying to link from Note B to Note A (after installing the plugin, obviously), I can use either "Note A" or "Linus" but I cannot use "Charlie Brown". Furthermore, even if the aliases value is empty, the alias from header functionality isn't working. Are these the expected behaviors?

Thanks,
Jack

**Comment by basham** [comment]
As [stated in the readme](https://github.com/basham/obsidian-alias-from-heading/blob/1.0.9/README.md?plain=1#L12):

> Any aliases defined in YAML continue to behave in their standard way.

The presence of a YAML alias does not disable the implicit heading alias. In your case, you should expect to have the following link suggestions when you type `[[`:

- `[[Note A]]`
- `[[Note A|Linus]]`
- `[[Note A|Charlie Brown]]`

Which suggestions you see of course depends on what you type after `[[`.

I discovered an issue with the plugin that resulted in the implicit heading alias not being added to the list of suggestions on loading the vault. If you are using this plugin, I suspect your thought on the behavior being disabled is actually a result of this bug. I released [v1.0.9](https://github.com/basham/obsidian-alias-from-heading/releases/tag/1.0.9) yesterday to resolve this.

Additionally, I thought of another issue that will need another bug fix (which also could have been the problem you are facing). As of v1.0.9, the entire vault will be scanned for these implicit heading aliases only if the plugin is loaded when the vault is loaded. If you installed the plugin and did not close and open the vault again, or if you disabled and then enabled the plugin — it likely has not rescanned the vault to provide the alias suggestions that you'd expect. So, until that fix is in place (likely a v1.0.10 release), please just restart Obsidian. Then it should work as expected.

Please let me know if any of this is helpful or (temporarily) addresses the issue you're facing.

**Comment by basham** [comment]
To help clarification, I can also update the readme to something like this:

> This alias is not explicitly defined in YAML. Any aliases defined in YAML continue to behave in their standard way and do not affect the behavior of this plugin.

**Comment by jebeaudoin** [comment]
Thanks for responding, Chris. Some additional information:

- I am using 1.09 of plugin. Obsidian Version 0.15.3 (installer 0.13.31)
- I am getting the same results after closing and reopening the vault.
- I created a "clean sandbox" with only BRAT and the obsidian-alias-from-heading plugin installed, and experiencing the same result. I've included screenshots.

## Note A
![Screen Shot 2022-06-29 at 2 31 44 PM](https://user-images.githubusercontent.com/10992411/176510475-b3994ce5-8580-45c6-a32c-3ad4468d3e0b.png)

## Note B
![Screen Shot 2022-06-29 at 2 34 00 PM](https://user-images.githubusercontent.com/10992411/176510657-615fde27-5647-41a9-8b84-85393fb41414.png)


If I remove the YAML from Note A, then the implicit alias from the first header works.
![Screen Shot 2022-06-29 at 2 36 16 PM](https://user-images.githubusercontent.com/10992411/176511088-fba1c00f-15b5-4de5-a79a-832e47f9bbce.png)


I hope this isn't a user error — I value your work and don't want to waste your time.

Jack

**Comment by basham** [comment]
I'm able to re-create the problem. Try updating `aliases` to `alias`. It should work, then.

I see that ["aliases" is what is mentioned in the official documentation](https://help.obsidian.md/How+to/Add+aliases+to+note). But it seems both words work (if this plugin is not enabled). The plugin is only accounting for "alias" for now. So, I need to test test different YAML configurations and others. I'll work on that fix, so it shouldn't be too particular in the future. Thanks for pointing it out!

**Comment by jebeaudoin** [comment]
I'm happy to be of assistance now and in the future. Not a coder, but a willing beta tester. Cheers!

**Comment by basham** [comment]
@jebeaudoin Please test the new 1.0.10 release. I believe it resolved all problems mentioned by us in this issue.

**Comment by jebeaudoin** [comment]
Hi Chris,

My test using a clean sandbox suggests that version 1.0.11 did not resolve the issue. The plugin works as expected if there is no alias (or aliases) declared in YAML. The presence of either alias or aliases in the frontmatter prevented the implicit alias from the header from working. I did quit and restart Obsidian several times during the testing, to no effect.

The only plugins in the sandbox are BRAT and obsidian-alias-from-heading.

Jack

**Comment by jebeaudoin** [comment]
Well, that was weird. Despite quitting and restarting several times, I was encountering the same bug in the sandbox vault. Then, I went back to it, changed the alias from "Lucy" to "Linus" and did a quit/restart cycle. And when it restarted, it worked as expected. I wonder if there was some kind of caching issue with Obsidian? Very weird.

But anyhow, it looks like it is working fine now. Thank you so much!

Jack
