### ISSUE TITLE
auto alias changing not working properly depending on link format settings

### ISSUE THREAD

**Issue by ghost** [basham/obsidian-alias-from-heading#8]
I'm sorry, but I've failed to find the consistent condition to replicate the bugs.

But when you try various link format settings and various folder structure,
you can find that there are some situations
which auto alias changing does not work properly.

Here's how I replicated bugs:
* Make some notes and make some links with title alias
  * Some notes can be in folders
* Change link format settings to one of followings:
  * Shortest path when possible
  * Relative path to file
  * Absolute path in vault
* Try changing post title
* Some aliases change, but some aliases don't.
* Keep trying various link format settings and various folder structure.
* Sometimes it works well, but sometimes it doesn't.

I don't know why this happens.
Could you figure it out?

**Comment by basham** [comment]
That's a good catch. I have not thoroughly tested this plugin for how it could work with notes in subfolders. My set up is flat, in which all my notes are in the same `notes` folder.

```
vault/
  attachments/
  notes/
  templates/
```

**Comment by ghost** [comment]
Is fixing this on the roadmap? Since I'm using folder structure I would be pleased if you make an update!

**Comment by basham** [comment]
This fix is the next piece of work for this plugin. I hope to resolve this by end of February.

**Comment by ghost** [comment]
was this update cancelled?

**Comment by basham** [comment]
No, this is still the next piece of work. I'm sorry for the delay. I've been swamped by life and other commitments.

**Comment by basham** [comment]
@cmasfo Please install v1.0.14 and check that the fix works for you.

(I apologize that it took me so long to start working on this issue. It was just a one-line fix that required a bit of investigation.)

**Comment by ghost** [comment]
worth long waiting, thank you!
